### ISSUE TITLE
Kernel not fully booting (TWRP)

### ISSUE THREAD

**Issue by alexenferman** [Hasaber8/twrp_device_motorola_ginna#1]
Hello, thanks electimon and Hasaber8  for the awesome work on this, 
however the kernel is not fully booting (I used the one from Moto and the one from Electimon Branch staging/AzurR7 ) and I am getting WLAN errors a lot of times judging by the kernel logs. Unfortunately I cannot post the log because it has disappeared from the phone and the command cat /sys/fs/pstore/console-ramoops-0 (using Root) does not display this log anymore :( 

Has anyone successfully built a working Kernel for this device?

Thanks!

**Comment by Hasaber8** [comment]
You have an ginna?
If yes please reply with your telegram I'd to this email. We would like to
get in touch with you.

**Comment by alexenferman** [comment]
I sent you a message through Telegram.
